### ISSUE TITLE
Annotating GenericAPIView.filter_queryset fails since v3.16.9

### ISSUE THREAD

**Issue by pai-martinreidemeister** [typeddjango/djangorestframework-stubs#965]
# Bug report

## What's wrong

I don't know how to annotate `rest_framework.generics.GenericAPIView.filter_queryset`. Before 3.16.9 we did this:
```python
from typing import override
from django.db.models import QuerySet
from rest_framework import viewsets
from foo.models import MyModel

class MyModelViewSet(viewsets.ModelViewSet[MyModel]):
    queryset = MyModel.objects.all()
    filterset_fields = ('name',)

    @override
    def filter_queryset(self, queryset: QuerySet[MyModel]) -> QuerySet[MyModel]:
        qs = super().filter_queryset(queryset)
        return qs
```

But since 3.16.9 we get this error:
```
$ mypy .
/path/to/foo/views_rest.py:12: error: Return type "QuerySet[MyModel, MyModel]" of "filter_queryset" incompatible with return type "QuerySet[MyModel, _Row]" in supertype
"rest_framework.generics.GenericAPIView"  [override]
        def filter_queryset(self, queryset: QuerySet[MyModel]) -> QuerySet[MyModel]:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/foo/views_rest.py:12: error: Argument 1 of "filter_queryset" is incompatible with supertype "rest_framework.generics.GenericAPIView"; supertype defines the argument type as
"QuerySet[MyModel, _Row]"  [override]
        def filter_queryset(self, queryset: QuerySet[MyModel]) -> QuerySet[MyModel]:
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/foo/views_rest.py:12: note: This violates the Liskov substitution principle
/path/to/foo/views_rest.py:12: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
Found 2 errors in 1 file (checked 13 source files)
```

I assume that #916 is the cause.

## How is that should be

There should be no error.

## System information

- OS:
- `python` version: 3.13.12
- `django` version: 6.0.3
- `mypy` version: 1.20.1
- `django-stubs` version: 6.0.2

**Comment by intgr** [comment]
@brianhelba any ideas?

**Comment by brianhelba** [comment]
Yes, I agree this was caused by #916.

I think that to be strictly correct, the downstream code should change to the two-argument generic syntax. However, requiring everyone to explicitly annotate all `QuerySet` using a two-argument form is a bad user experience. Python type annotations have a bad reputation even when they're simple and intuitive, and the two-argument syntax is not obvious at first (to be fair, the syntax is ultimately dictated by Django's behavior and the model created by `django-stubs`, which we can't control).

So, I'm open to reverting some or all of #916, but let me see if there's any possible workarounds that we could add upstream.

**Comment by brianhelba** [comment]
Note, in Python 3.12+, the strictly correct syntax is a bit less awkward (since `TypeVar` isn't needed):
```python                                
  class MyModelViewSet(viewsets.ModelViewSet[MyModel]):
      @override
      def filter_queryset[MyModelRow](self, queryset: QuerySet[MyModel, MyModelRow]) -> QuerySet[MyModel, MyModelRow]:
          ...
```
I still don't think this is intuitive for most users.
