### PR TITLE
Make remaining fields accept default=None/initial=None

### PR DESCRIPTION
**Pull request by intgr**
ChoiceField, MultipleChoiceField, FilePathField, FileField, ImageField, ListField, DictField, HStoreField, JSONField were previously using hard-coded `default` and `initial` constructor argument types.

Adapted the `_DefaultInitial[]` type alias instead -- introduced in PR #101 -- which allows `None`.

### CODE REVIEW

File: tests/typecheck/test_fields.yml [hunk 1]
```diff
@@ -78,15 +78,86 @@
         x: Optional[str] = CharField().get_initial()
         y: Optional[int] = CharField().get_initial()  # E: Incompatible types in assignment (expression has type "Optional[str]", variable has type "Optional[int]")
 
-        MultipleChoiceField(choices=[(1, "1"), (2, "2")], default={1})
-        MultipleChoiceField(choices=[(1, "1"), (2, "2")], default=[1])  # E: Argument "default" to "MultipleChoiceField" has incompatible type "List[int]"; expected "Union[_Empty, Set[str], Set[int], Callable[[], Set[str]], Callable[[], Set[int]]]"
-
-        MultipleChoiceField(choices=[(1, "1"), (2, "2")], initial={1})
-        MultipleChoiceField(choices=[(1, "1"), (2, "2")], initial=[1])  # E: Argument "initial" to "MultipleChoiceField" has incompatible type "List[int]"; expected "Union[_Empty, Set[str], Set[int], Callable[[], Set[str]], Callable[[], Set[int]]]"
```
Comment (intgr) [inline tests/typecheck/test_fields.yml:85]: I moved these tests to the separate `MultipleChoiceField_default` test case.

File: rest_framework-stubs/fields.pyi [hunk 2]
```diff
@@ -514,12 +514,8 @@ class MultipleChoiceField(
...
         write_only: bool = ...,
         required: bool = ...,
-        default: Union[
-            _Empty, Set[str], Set[int], Callable[[], Set[str]], Callable[[], Set[int]]
-        ] = ...,
-        initial: Union[
-            _Empty, Set[str], Set[int], Callable[[], Set[str]], Callable[[], Set[int]]
-        ] = ...,
+        default: _DefaultInitial[Union[Set[Union[str, int]], Set[str], Set[int]]] = ...,
+        initial: _DefaultInitial[Union[Set[Union[str, int]], Set[str], Set[int]]] = ...,
```
Comment (intgr) [inline rest_framework-stubs/fields.pyi:518]: Since `Set` is mutable, `Set[str]` is not compatible with `Set[Union[str, int]]`. So I explicitly allowed all three combinations:
* `Set[Union[str, int]]`
* `Set[str]`
* `Set[int]`

**Review by sobolevn — APPROVED** [review]
Great work, thank you!
